name: 'Terraform GitHub Actions CI'

on:
  - pull_request
  
env:
  tf_version: "latest"
  tf_working_dir: "."

jobs:
  ci:
    name: Test CI
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_auth_password: ${{secrets.AUTH_PASSWORD}}
      TF_VAR_auth_username: ${{secrets.AUTH_USERNAME}}
      TF_VAR_db_name: ${{secrets.DB_NAME}}
      TF_VAR_db_passwd: ${{secrets.DB_PASSWORD}}
      TF_VAR_db_username:  ${{secrets.DB_USERNAME}}
      TF_VAR_github_token: ${{secrets.GITHUB_TOKEN_ORG}}
      TF_VAR_jwt_secret_key: ${{secrets.JWT_SECRET_KEY}}
      TF_VAR_repository_name: "hummingbird-v2"
      TF_VAR_repository_owner: "CovidZero"
      TF_VAR_cloudflare_api_token: ${{secrets.CLOUDFLARE_API_TOKEN}}

    steps:
    - name: "Code Checkout"
      uses: actions/checkout@v1

    - name: "Terraform Init"
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.21
        tf_actions_subcommand: "init"

    - name: "Terraform Validate"
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.21
        tf_actions_subcommand: "validate"

    - name: "Terraform Plan"
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.21
        tf_actions_subcommand: "plan"
    